[package]
name = "gnome-search-providers-vscode"
description = "Gnome search providers for recent workspace in VSCode variants"
readme = "README.md"
homepage = "https://github.com/lunaryorn/gnome-search-providers-vscode"
repository = "https://github.com/lunaryorn/gnome-search-providers-vscode"
version = "1.5.1-alpha.0"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
# We don't publish this to crates.io; you can't install it with cargo install
# because you'd miss the required service and configuration files, and you
# wouldn't want to depend on it either.
publish = false

[dependencies]
dirs = "3.0.1"
anyhow = "^1.0"
clap = "^2.33"
log = { version = "^0.4", features = ["release_max_level_info"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
gnome-search-provider-common = { git = "https://github.com/lunaryorn/gnome-search-providers-jetbrains.git", tag = "v1.7.1" }

[dev-dependencies]
pretty_assertions = "^0.7"
rust-ini = "^0.17"
globwalk = "^0.8"

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Bump version to {{next_version}}"
tag-prefix = ""
tag-message = "Version {{tag_name}}"
pre-release-replacements = [
    # Update the changelog
    { file="CHANGELOG.md", search="## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] – {{date}}", exactly = 1 },
    { file="CHANGELOG.md", search="HEAD", replace = "{{tag_name}}", exactly = 1 },
    { file="CHANGELOG.md", search="\\[Unreleased\\]: ", replace = "[Unreleased]: https://github.com/lunaryorn/gnome-search-providers-vscode/compare/{{tag_name}}...HEAD\n[{{version}}]: ", exactly = 1 },
]
publish = false
